CREATE TABLE RefreshTokens
(
	ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_RefreshTokens_ID DEFAULT (NEWID()),
	Token NVARCHAR(100) NOT NULL,
	ExpiresAt DATETIME2 NOT NULL,
	CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_RefreshTokens_CreatedAt DEFAULT (SYSUTCDATETIME()),
	RevokedAt DATETIME2 NULL,
	UserID UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_RefreshTokens PRIMARY KEY (ID ASC),
	CONSTRAINT FK_RefreshTokens_Users_UserID FOREIGN KEY (UserID) REFERENCES Users (ID) ON DELETE CASCADE
);
