CREATE TABLE Roles
(
	ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Roles_ID DEFAULT (NEWID()),
	Name NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_Roles PRIMARY KEY (ID ASC),
	INDEX IX_Roles_Name UNIQUE NONCLUSTERED (Name ASC)
);
