CREATE TABLE UserRoles
(
	UserID UNIQUEIDENTIFIER NOT NULL,
	RoleID UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_UserRoles PRIMARY KEY (UserID ASC, RoleID ASC),
	CONSTRAINT FK_UserRoles_Users_UserID FOREIGN KEY (UserID) REFERENCES Users (ID) ON DELETE CASCADE,
	CONSTRAINT FK_UserRoles_Roles_RoleID FOREIGN KEY (RoleID) REFERENCES Roles (ID) ON DELETE CASCADE
);
