CREATE TABLE UserLogs
(
	ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_UserLogs_ID DEFAULT (NEWID()),
	UserID UNIQUEIDENTIFIER NOT NULL,
	EventType INT NOT NULL,
	Timestamp DATETIME2 NOT NULL CONSTRAINT DF_UserLogs_Timestamp DEFAULT (SYSUTCDATETIME()),
	IpAddress NVARCHAR(45) NOT NULL,
	Success BIT NOT NULL,
	CONSTRAINT PK_UserLogs PRIMARY KEY (ID ASC),
	CONSTRAINT FK_UserLogs_Users_UserID FOREIGN KEY (UserID) REFERENCES Users (ID) ON DELETE CASCADE
);
