CREATE TABLE Users
(
	ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Users_ID DEFAULT (NEWID()),
	Username NVARCHAR(30) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	PasswordHash NVARCHAR(60) NOT NULL,
	CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2 NULL,
	FileID UNIQUEIDENTIFIER NULL,
	CONSTRAINT PK_Users PRIMARY KEY (ID ASC),
	CONSTRAINT FK_Users_UploadedFiles_FileID FOREIGN KEY (FileID) REFERENCES UploadedFiles (ID) ON DELETE SET NULL,
	INDEX IX_Users_Username UNIQUE NONCLUSTERED (Username ASC),
	INDEX IX_Users_Email UNIQUE NONCLUSTERED (Email ASC)
);
