<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>7c66ed6d-587a-44f9-aa09-eef14a405bd0</UserSecretsId>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.IDentityModel.JsonWebTokens" Version="8.17.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BookFlix.Core\BookFlix.Core.csproj" />
		<ProjectReference Include="..\BookFlix.Infrastructure\BookFlix.Infrastructure.csproj" />
	</ItemGroup>

</Project>