services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=BookFlixDBPassword123!
    ports:
      - "1433:1433"

  db-migrator:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./efbundle", "--connection", "Server=db;Database=BookFlix;User Id=sa;Password=BookFlixDBPassword123!;TrustServerCertificate=True;"]
    depends_on:
      db:
        condition: service_started

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=BookFlix;User Id=sa;Password=BookFlixDBPassword123!;TrustServerCertificate=True;
      - Jwt__Key=BookFlixSuperSecretSecurityKey1234567890!
    depends_on:
      db-migrator:
        condition: service_completed_successfully
