using BookFlix.Core.Abstractions;
using BookFlix.Core.Models;
using BookFlix.Core.Repositories;
using BookFlix.Core.Services.Validation;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Hosting;

namespace BookFlix.Core.Service_Interfaces
{
    public interface IFileService<T> where T : class, IEntityFile
    {
        Task<Result<Guid>> UploadFileAsync(Guid entityID, IFormFile file);
        Result ValidateFile(IFormFile file);
        Task<Result<string>> GetFilePathAsync(Guid fileId);
    }

    public abstract class FileService<T> : IFileService<T> where T : class, IEntityFile
    {
        private readonly IEntityfileRepository<T> _repository;
        private readonly IUploadedFileRepository _uploadedFileRepository;
        private readonly ILogger<FileService<T>> _logger;
        private readonly IWebHostEnvironment _environment;
        private string _directory;

        public abstract string FolderName { get; }

        protected FileService(
            IEntityfileRepository<T> repository, 
            IUploadedFileRepository uploadedFileRepository, 
            ILogger<FileService<T>> logger,
            IWebHostEnvironment environment)
        {
            _repository = repository;
            _uploadedFileRepository = uploadedFileRepository;
            _logger = logger;
            _environment = environment;
            SetDirectory();
        }

        public abstract Result ValidateFile(IFormFile file);

        public async Task<Result<Guid>> UploadFileAsync(Guid entityID, IFormFile file)
        {
            var result = ValidateFile(file);
            if (result.IsFailure) return Result.Failure<Guid>(result.Error);

            var entity = await _repository.GetByIDAsync(entityID);
            if (entity is null)
            {
                _logger.LogError("{EntityType} with ID {EntityID} not found.", typeof(T).Name, entityID);
                return Result.Failure<Guid>(Error.NotFound($"{typeof(T).Name}NotFound"));
            }

            string filePath = null;
            UploadedFile uploadedFile = null;

            using var transaction = await _repository.BeginTransactionAsync();
            try
            {
                if (entity.FileID.HasValue)
                {
                    uploadedFile = await _uploadedFileRepository.GetByIDAsync(entity.FileID.Value);
                    if (uploadedFile is not null)
                    {
                        filePath = Path.Combine(_directory, uploadedFile.FileLocation);
                        var deleteResult = DeleteFile(filePath);
                        if (deleteResult.IsFailure) return Result.Failure<Guid>(deleteResult.Error);
                    }
                }

                filePath = SetAutoGeneratedFileName(file.FileName);
                await SaveFileToDirectory(file, filePath);

                var fileNameAsFileLocation = Path.GetFileName(filePath);

                if (uploadedFile is null)
                {
                    uploadedFile = new UploadedFile
                    {
                        ID = Guid.NewGuid(),
                        FileLocation = fileNameAsFileLocation,
                        ContentType = file.ContentType,
                        CreatedAt = DateTime.UtcNow
                    };
                    await _uploadedFileRepository.AddAsync(uploadedFile);
                    await _uploadedFileRepository.SaveChangesAsync();
                }
                else
                {
                    uploadedFile.FileLocation = fileNameAsFileLocation;
                    uploadedFile.ContentType = file.ContentType;
                    uploadedFile.UpdatedAt = DateTime.UtcNow;
                    await _uploadedFileRepository.SaveChangesAsync();
                }

                await _repository.UpdateFileIDAsync(entityID, uploadedFile.ID);
                await _repository.SaveChangesAsync();
                await transaction.CommitAsync();

                return Result.Success(uploadedFile.ID);
            }
            catch (IOException ex)
            {
                await transaction.RollbackAsync();
                DeleteFile(filePath);
                _logger.LogError(ex, "IO error uploading file for {EntityType} ID {EntityID}", typeof(T).Name, entityID);
                return Result.Failure<Guid>(Error.Failure("FileSaveStorageError"));
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                _logger.LogError(ex, "Unexpected error uploading file for {EntityType} ID {EntityID}", typeof(T).Name, entityID);
                return Result.Failure<Guid>(Error.Failure("FileUnexpectedUploadError"));
            }
        }

        public async Task<Result<string>> GetFilePathAsync(Guid fileId)
        {
            var uploadedFile = await _uploadedFileRepository.GetByIDAsync(fileId);
            if (uploadedFile is null)
            {
                return Result.Failure<string>(Error.NotFound("FileNotFound"));
            }

            var filePath = Path.Combine(_directory, uploadedFile.FileLocation);
            if (!File.Exists(filePath))
            {
                return Result.Failure<string>(Error.NotFound("FileNotFound"));
            }

            return Result.Success(filePath);
        }

        private static async Task SaveFileToDirectory(IFormFile file, string filePath)
        {
            var directory = Path.GetDirectoryName(filePath) ?? throw new InvalidOperationException("Invalid file path.");
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            using var stream = new FileStream(filePath, FileMode.Create);
            await file.CopyToAsync(stream);
        }

        private string SetAutoGeneratedFileName(string originalFileName)
        {
            string ext = Path.GetExtension(originalFileName);
            string fileName = $"{Guid.NewGuid()}{ext}";
            return Path.Combine(_directory, fileName);
        }

        private Result DeleteFile(string fileLocation)
        {
            if (!string.IsNullOrEmpty(fileLocation))
            {
                var fullFileLocation = Path.Combine(_directory, Path.GetFileName(fileLocation));
                if (File.Exists(fullFileLocation))
                {
                    try
                    {
                        File.Delete(fullFileLocation);
                    }
                    catch (IOException ex)
                    {
                        _logger.LogError(ex, "IO error deleting file: {FileLocation}", fileLocation);
                        return Result.Failure(Error.Failure("FileDeletionFailed"));
                    }
                }
            }
            return Result.Success();
        }

        private void SetDirectory()
        {
            string folderPath = Path.Combine(_environment.ContentRootPath, FolderName);
            if (!Directory.Exists(folderPath)) Directory.CreateDirectory(folderPath);
            _directory = folderPath;
        }
    }
}
