using BookFlix.Core.Abstractions;
using BookFlix.Core.Repositories;
using BookFlix.Core.Services.Validation;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace BookFlix.Core.Service_Interfaces
{
    public interface IFileService<T> where T : class, IEntityFile
    {
        Task<Result<string>> UploadFileAsync(Guid entityID, IFormFile file);
        Result ValidateFile(IFormFile file);
    }

    public abstract class FileService<T> : IFileService<T> where T : class, IEntityFile
    {
        private readonly IEntityfileRepository<T> _repository;
        private readonly ILogger<FileService<T>> _logger;
        private string _directory;

        public abstract string FolderName { get; }

        protected FileService(IEntityfileRepository<T> repository, ILogger<FileService<T>> logger)
        {
            _repository = repository;
            _logger = logger;
            SetDirectory();
        }

        public abstract Result ValidateFile(IFormFile file);

        public async Task<Result<string>> UploadFileAsync(Guid entityID, IFormFile file)
        {
            var result = ValidateFile(file);
            if (result.IsFailure) return Result.Failure<string>(result.Error);

            var entity = await _repository.GetByIDAsync(entityID);
            if (entity is null)
            {
                _logger.LogError("{EntityType} with ID {EntityID} not found.", typeof(T).Name, entityID);
                return Result.Failure<string>(Error.NotFound($"{typeof(T).Name}NotFound"));
            }

            string filePath = null;
            using var transaction = await _repository.BeginTransactionAsync();
            try
            {
                filePath = entity.FileLocation != null ? Path.Combine(_directory, entity.FileLocation) : null;

                result = DeleteFile(filePath);
                if (result.IsFailure) return Result.Failure<string>(result.Error);

                filePath = SetAutoGeneratedFileName(file.FileName);
                await SaveFileToDirectory(file, filePath);

                var fileNameAsFileLocation = Path.GetFileName(filePath);
                await _repository.UpdateFileLocationAsync(entityID, fileNameAsFileLocation);
                await transaction.CommitAsync();

                return Result.Success(fileNameAsFileLocation);
            }
            catch (IOException ex)
            {
                await transaction.RollbackAsync();
                DeleteFile(filePath);
                _logger.LogError(ex, "IO error uploading file for {EntityType} ID {EntityID}", typeof(T).Name, entityID);
                return Result.Failure<string>(Error.Failure("FileSaveStorageError"));
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                _logger.LogError(ex, "Unexpected error uploading file for {EntityType} ID {EntityID}", typeof(T).Name, entityID);
                return Result.Failure<string>(Error.Failure("FileUnexpectedUploadError"));
            }
        }

        private static async Task SaveFileToDirectory(IFormFile file, string filePath)
        {
            var directory = Path.GetDirectoryName(filePath) ?? throw new InvalidOperationException("Invalid file path.");
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            using var stream = new FileStream(filePath, FileMode.Create);
            await file.CopyToAsync(stream);
        }

        private string SetAutoGeneratedFileName(string originalFileName)
        {
            string ext = Path.GetExtension(originalFileName);
            string fileName = $"{Guid.NewGuid()}{ext}";
            return Path.Combine(_directory, fileName);
        }

        private Result DeleteFile(string fileLocation)
        {
            if (!string.IsNullOrEmpty(fileLocation))
            {
                var fullFileLocation = Path.Combine(_directory, Path.GetFileName(fileLocation));
                if (File.Exists(fullFileLocation))
                {
                    try
                    {
                        File.Delete(fullFileLocation);
                    }
                    catch (IOException ex)
                    {
                        _logger.LogError(ex, "IO error deleting file: {FileLocation}", fileLocation);
                        return Result.Failure(Error.Failure("FileDeletionFailed"));
                    }
                }
            }
            return Result.Success();
        }

        private void SetDirectory()
        {
            string folderPath = Path.Combine(Directory.GetCurrentDirectory(), FolderName);
            if (!Directory.Exists(folderPath)) Directory.CreateDirectory(folderPath);
            _directory = folderPath;
        }
    }
}
