CREATE TABLE Authors
(
	ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Authors_ID DEFAULT (NEWID()),
	Name NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_Authors PRIMARY KEY (ID ASC),
	INDEX IX_Authors_Name UNIQUE NONCLUSTERED (Name ASC)
);
