CREATE TABLE Books
(
	ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Books_ID DEFAULT (NEWID()),
	Title NVARCHAR(150) NOT NULL,
	Description NVARCHAR(1000) NULL,
	ISBN NVARCHAR(20) NULL,
	CoverImageUrl NVARCHAR(500) NULL,
	PublicationDate DATETIME NULL,
	Publisher NVARCHAR(100) NULL,
	PageCount INT NULL,
	AverageRating DECIMAL(3, 2) NOT NULL CONSTRAINT DF_Books_AverageRating DEFAULT (0),
	IsAvailable BIT NOT NULL CONSTRAINT DF_Books_IsAvailable DEFAULT (1),
	CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Books_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2 NULL,
	FileID UNIQUEIDENTIFIER NULL,
	CONSTRAINT PK_Books PRIMARY KEY (ID ASC),
	CONSTRAINT FK_Books_UploadedFiles_FileID FOREIGN KEY (FileID) REFERENCES UploadedFiles (ID) ON DELETE SET NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX IX_Books_ISBN
	ON Books (ISBN ASC)
	WHERE ISBN IS NOT NULL;
