CREATE TABLE BookAuthors
(
	BookID UNIQUEIDENTIFIER NOT NULL,
	AuthorID UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_BookAuthors PRIMARY KEY (BookID ASC, AuthorID ASC),
	CONSTRAINT FK_BookAuthors_Books_BookID FOREIGN KEY (BookID) REFERENCES Books (ID) ON DELETE CASCADE,
	CONSTRAINT FK_BookAuthors_Authors_AuthorID FOREIGN KEY (AuthorID) REFERENCES Authors (ID) ON DELETE CASCADE
);
