CREATE TABLE BookGenres
(
	BookID UNIQUEIDENTIFIER NOT NULL,
	GenreID INT NOT NULL,
	CONSTRAINT PK_BookGenres PRIMARY KEY (BookID ASC, GenreID ASC),
	CONSTRAINT FK_BookGenres_Books_BookID FOREIGN KEY (BookID) REFERENCES Books (ID) ON DELETE CASCADE,
	CONSTRAINT FK_BookGenres_Genres_GenreID FOREIGN KEY (GenreID) REFERENCES Genres (ID) ON DELETE CASCADE
);
