CREATE TABLE Reviews
(
	ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Reviews_ID DEFAULT (NEWID()),
	Content NVARCHAR(255) NULL,
	Rating TINYINT NOT NULL,
	CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Reviews_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2 NULL,
	BookID UNIQUEIDENTIFIER NOT NULL,
	UserID UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_Reviews PRIMARY KEY (ID ASC),
	CONSTRAINT FK_Reviews_Books_BookID FOREIGN KEY (BookID) REFERENCES Books (ID) ON DELETE CASCADE,
	CONSTRAINT FK_Reviews_Users_UserID FOREIGN KEY (UserID) REFERENCES Users (ID) ON DELETE CASCADE
);
