CREATE TABLE UploadedFiles
(
	ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_UploadedFiles_ID DEFAULT (NEWID()),
	FileLocation NVARCHAR(255) NOT NULL,
	ContentType NVARCHAR(100) NOT NULL,
	CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_UploadedFiles_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2 NULL,
	CONSTRAINT PK_UploadedFiles PRIMARY KEY (ID ASC)
);
