// <auto-generated />
using System;
using BookFlix.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookFlix.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711133314_AddUploadedFilesTable")]
    partial class AddUploadedFilesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookFlix.Core.Models.Author", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            ID = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "Harper Lee"
                        },
                        new
                        {
                            ID = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Name = "George Orwell"
                        },
                        new
                        {
                            ID = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Name = "Jane Austen"
                        },
                        new
                        {
                            ID = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            ID = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Name = "Frank Herbert"
                        },
                        new
                        {
                            ID = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Name = "Yuval Noah Harari"
                        },
                        new
                        {
                            ID = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Name = "Dan Brown"
                        });
                });

            modelBuilder.Entity("BookFlix.Core.Models.Book", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("FileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("FileID");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("b0000000-0000-0000-0000-000000000001"),
                            AverageRating = 4.20m,
                            CoverImageUrl = "https://example.com/great-gatsby.jpg",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A novel set in the Roaring Twenties.",
                            ISBN = "9780743273565",
                            IsAvailable = true,
                            PageCount = 180,
                            PublicationDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Scribner",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            ID = new Guid("b0000000-0000-0000-0000-000000000002"),
                            AverageRating = 4.30m,
                            CoverImageUrl = "https://example.com/to-kill-a-mockingbird.jpg",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A novel about racial injustice in the Deep South.",
                            ISBN = "9780061120084",
                            IsAvailable = true,
                            PageCount = 281,
                            PublicationDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "J.B. Lippincott & Co.",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            ID = new Guid("b0000000-0000-0000-0000-000000000003"),
                            AverageRating = 4.40m,
                            CoverImageUrl = "https://example.com/1984.jpg",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A dystopian novel about totalitarianism.",
                            ISBN = "9780451524935",
                            IsAvailable = true,
                            PageCount = 328,
                            PublicationDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Secker & Warburg",
                            Title = "1984"
                        },
                        new
                        {
                            ID = new Guid("b0000000-0000-0000-0000-000000000004"),
                            AverageRating = 4.25m,
                            CoverImageUrl = "https://example.com/pride-and-prejudice.jpg",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A romantic novel about love and social class.",
                            ISBN = "9780141439518",
                            IsAvailable = true,
                            PageCount = 432,
                            PublicationDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Penguin Classics",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            ID = new Guid("b0000000-0000-0000-0000-000000000005"),
                            AverageRating = 4.27m,
                            CoverImageUrl = "https://example.com/the-hobbit.jpg",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A fantasy adventure about Bilbo Baggins.",
                            ISBN = "9780547928227",
                            IsAvailable = true,
                            PageCount = 310,
                            PublicationDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Houghton Mifflin",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            ID = new Guid("b0000000-0000-0000-0000-000000000006"),
                            AverageRating = 4.21m,
                            CoverImageUrl = "https://example.com/dune.jpg",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A science fiction epic about a desert planet.",
                            ISBN = "9780441172719",
                            IsAvailable = true,
                            PageCount = 412,
                            PublicationDate = new DateTime(1965, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Ace Books",
                            Title = "Dune"
                        },
                        new
                        {
                            ID = new Guid("b0000000-0000-0000-0000-000000000007"),
                            AverageRating = 4.38m,
                            CoverImageUrl = "https://example.com/sapiens.jpg",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A nonfiction exploration of human history.",
                            ISBN = "9780062316097",
                            IsAvailable = true,
                            PageCount = 443,
                            PublicationDate = new DateTime(2014, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Harper",
                            Title = "Sapiens: A Brief History of Humankind"
                        },
                        new
                        {
                            ID = new Guid("b0000000-0000-0000-0000-000000000008"),
                            AverageRating = 3.85m,
                            CoverImageUrl = "https://example.com/da-vinci-code.jpg",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A thriller involving a religious conspiracy.",
                            ISBN = "9780307277671",
                            IsAvailable = true,
                            PageCount = 454,
                            PublicationDate = new DateTime(2003, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Doubleday",
                            Title = "The Da Vinci Code"
                        });
                });

            modelBuilder.Entity("BookFlix.Core.Models.BookAuthor", b =>
                {
                    b.Property<Guid>("BookID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookID", "AuthorID");

                    b.HasIndex("AuthorID");

                    b.ToTable("BookAuthors", (string)null);

                    b.HasData(
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000001"),
                            AuthorID = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000002"),
                            AuthorID = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000003"),
                            AuthorID = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000004"),
                            AuthorID = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000005"),
                            AuthorID = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000006"),
                            AuthorID = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000007"),
                            AuthorID = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000008"),
                            AuthorID = new Guid("a0000000-0000-0000-0000-000000000008")
                        });
                });

            modelBuilder.Entity("BookFlix.Core.Models.BookGenre", b =>
                {
                    b.Property<Guid>("BookID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("BookID", "GenreID");

                    b.HasIndex("GenreID");

                    b.ToTable("BookGenres", (string)null);

                    b.HasData(
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000001"),
                            GenreID = 1
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000002"),
                            GenreID = 1
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000003"),
                            GenreID = 3
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000004"),
                            GenreID = 7
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000004"),
                            GenreID = 8
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000005"),
                            GenreID = 4
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000005"),
                            GenreID = 19
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000006"),
                            GenreID = 3
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000007"),
                            GenreID = 2
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000007"),
                            GenreID = 14
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000008"),
                            GenreID = 6
                        },
                        new
                        {
                            BookID = new Guid("b0000000-0000-0000-0000-000000000008"),
                            GenreID = 5
                        });
                });

            modelBuilder.Entity("BookFlix.Core.Models.Genre", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Nonfiction"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Mystery"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Thriller"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Biography"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Autobiography"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Self-Help"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Business"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Science"
                        },
                        new
                        {
                            ID = 14,
                            Name = "History"
                        },
                        new
                        {
                            ID = 15,
                            Name = "Young Adult"
                        },
                        new
                        {
                            ID = 16,
                            Name = "Children"
                        },
                        new
                        {
                            ID = 17,
                            Name = "Poetry"
                        },
                        new
                        {
                            ID = 18,
                            Name = "Horror"
                        },
                        new
                        {
                            ID = 19,
                            Name = "Adventure"
                        },
                        new
                        {
                            ID = 20,
                            Name = "Crime"
                        },
                        new
                        {
                            ID = 21,
                            Name = "Literary Criticism"
                        },
                        new
                        {
                            ID = 22,
                            Name = "Cooking"
                        },
                        new
                        {
                            ID = 23,
                            Name = "Travel"
                        },
                        new
                        {
                            ID = 24,
                            Name = "Philosophy"
                        },
                        new
                        {
                            ID = 25,
                            Name = "Religion"
                        });
                });

            modelBuilder.Entity("BookFlix.Core.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BookFlix.Core.Models.Review", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("BookID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("BookFlix.Core.Models.Role", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("32684285-5ff9-486d-a2a4-de00bdea2d20"),
                            Name = "Admin"
                        },
                        new
                        {
                            ID = new Guid("2abd05f3-fc73-4a5f-a3b5-01291030851f"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("BookFlix.Core.Models.UploadedFile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("UploadedFiles", (string)null);
                });

            modelBuilder.Entity("BookFlix.Core.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("FileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FileID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("3dba3903-21a6-413d-a479-eb807eb5e6ed"),
                            CreatedAt = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$IAzmX9gT.qkqm45lMnyh/uE0PZ793GOyIKEEn3dNdbAC1cfxcbFVa",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BookFlix.Core.Models.UserLog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("UserLogs", (string)null);
                });

            modelBuilder.Entity("BookFlix.Core.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = new Guid("3dba3903-21a6-413d-a479-eb807eb5e6ed"),
                            RoleID = new Guid("32684285-5ff9-486d-a2a4-de00bdea2d20")
                        });
                });

            modelBuilder.Entity("BookFlix.Core.Models.Book", b =>
                {
                    b.HasOne("BookFlix.Core.Models.UploadedFile", "File")
                        .WithMany()
                        .HasForeignKey("FileID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("File");
                });

            modelBuilder.Entity("BookFlix.Core.Models.BookAuthor", b =>
                {
                    b.HasOne("BookFlix.Core.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlix.Core.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookFlix.Core.Models.BookGenre", b =>
                {
                    b.HasOne("BookFlix.Core.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlix.Core.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookFlix.Core.Models.RefreshToken", b =>
                {
                    b.HasOne("BookFlix.Core.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookFlix.Core.Models.Review", b =>
                {
                    b.HasOne("BookFlix.Core.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlix.Core.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookFlix.Core.Models.User", b =>
                {
                    b.HasOne("BookFlix.Core.Models.UploadedFile", "File")
                        .WithMany()
                        .HasForeignKey("FileID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("File");
                });

            modelBuilder.Entity("BookFlix.Core.Models.UserLog", b =>
                {
                    b.HasOne("BookFlix.Core.Models.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookFlix.Core.Models.UserRole", b =>
                {
                    b.HasOne("BookFlix.Core.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlix.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookFlix.Core.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BookFlix.Core.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("UserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
